// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGv10Cne8SarpkqPjFyfKQilPisfW83Xk',
    appId: '1:899080782548:web:ac210c83112e799737f141',
    messagingSenderId: '899080782548',
    projectId: 'eprojectwatchhub',
    authDomain: 'eprojectwatchhub.firebaseapp.com',
    storageBucket: 'eprojectwatchhub.appspot.com',
    measurementId: 'G-4Y6HNT7K3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZUtjSKfbVsGUEAMPApbeW9qavcrgGqI',
    appId: '1:899080782548:android:44af5bab1c0c099c37f141',
    messagingSenderId: '899080782548',
    projectId: 'eprojectwatchhub',
    storageBucket: 'eprojectwatchhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfP9OdFubvHJ-BbmLy1ESJTcpYAoBPzCQ',
    appId: '1:899080782548:ios:8fcda42bec66101b37f141',
    messagingSenderId: '899080782548',
    projectId: 'eprojectwatchhub',
    storageBucket: 'eprojectwatchhub.appspot.com',
    iosBundleId: 'com.example.eProjectWatchHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfP9OdFubvHJ-BbmLy1ESJTcpYAoBPzCQ',
    appId: '1:899080782548:ios:e41c1befefbcfaa237f141',
    messagingSenderId: '899080782548',
    projectId: 'eprojectwatchhub',
    storageBucket: 'eprojectwatchhub.appspot.com',
    iosBundleId: 'com.example.eProjectWatchHub.RunnerTests',
  );
}
